### ISSUE TITLE
Implement User Registration

### ISSUE THREAD

**Issue by iluxonchik** [iluxonchik/sirs-project-android-client#5]
Implement the user registration part: includes sending/recieving of Bluetooth messages to/from the server

**Comment by PastelBelem8** [comment]
Implement a module<X> that will be responsible for the protocol implementation (send, receive, ... ) with the server 
- [x] Validate Username: Alphanumerical and _ only
- [x] Validate Password: (Requires #3) 
- [x] Send to Module<X>

Actually implement: 
- [x] SEND  (Add PKDF2 to Password) (verify sketches Illya has made)

- [x] RECEIVE
