### ISSUE TITLE
Post-login server communication with token

### ISSUE THREAD

**Issue by iluxonchik** [iluxonchik/sirs-project-android-client#8]
Communication with server after the user has obtained the token: all of the messages sent to the server will include the token the the server gave to the user.

**NOTE:** all of the messages sent to the server, except for the password login ( #7 ) and registration ( #5 ) will have a token sent alongside them, which servers as an authenticatior.

**Comment by PastelBelem8** [comment]
Missing Nonce checks, in order to prevent replay attacks

**Comment by iluxonchik** [comment]
@PastelBelem8 oh yeah, we're using the counter as the `IV`, correct?

**Comment by PastelBelem8** [comment]
@iluxonchik  yes. Should we have one for incoming and other for outcoming?
